# ---
# apiVersion: v1
# kind: Service
# metadata:
   # name: mongo-svc-a
# labels:
   # name: mongo-svc-a
# spec:
   # type: LoadBalancer
   # ports:
   # - port: 27017
      # targetPort: 27017
      # protocol: TCP
      # name: mongo-svc-a
   # selector:
       # name: mongo   
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - port: 9042
    targetPort: 9042
  selector:
    app: cassandra
---
# apiVersion: v1
# kind: Service
# metadata:
  # name: dev
  # labels:
    # app: dev
# spec:
  # type: LoadBalancer
  # ports:
  # - port: 8080
    # targetPort: 8080
  # selector:
    # app: dev
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
  - port: 9999
    targetPort: 9999
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: eureka-service