server:
  port: 8070
spring:
  application:
    name: wsTest-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.122.70:8761/eureka/
  instance:
    prefer-ip-address: true


# todo non so se sia corretto
test:
  ws: ws://192.168.122.82:8020/events/websock