server:
  port: 8070
spring:
  application:
    name: wsTest-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.122.87:8761/eureka/
  instance:
    prefer-ip-address: true


# todo non so se sia corretto
test:
  ws: ws://192.168.122.82:8020/events/websocket
  path: /opt/Bambino_Freddo.mp4
logging:
  file: ${spring.application.name}.log